import Head from "next/head"
import { GetServerSideProps } from "next"
import dbConnect from "../../lib/dbConnect"
import Recipe from "../../models/Recipe"
import Category from "../../models/Category"
import Ingredient from "../../models/Ingredient"
import RecipeShow from "../../components/RecipeShow"

export default function index({ recipe, ingredients , categories }) {
    
    return (
        <div>
            <Head>
            <title>  </title>
            <meta name="description" content="Generated by create next app" />
            </Head>
            {JSON.stringify(recipe)}
            <RecipeShow recipe={recipe} ingredients={ingredients} categories={categories} />
        </div>
    )
}

export const getServerSideProps : GetServerSideProps = async ({params}) => {
   
    await dbConnect();
    const recipe = await Recipe.findById(params.id).lean()

    const ingredients = await Ingredient.find({}).where('recipe_id').equals(recipe._id).lean()
    const categories = await Category.find({}).where('recipe_id').equals(recipe._id).lean()

    return {props: { 
        recipe:{...recipe, _id: recipe._id.toString()},
        ingredients: JSON.parse(JSON.stringify(ingredients)),
        categories: JSON.parse(JSON.stringify(categories)) 
    }}
}