import Head from 'next/head'
import { useRouter } from 'next/router'
import { GetServerSideProps } from 'next'
import dbConnect from "../../lib/dbConnect"
import Recipe from "../../models/Recipe"


export default function index({ recipe }) {
    
    // const router = useRouter()
    // const { id } = router.query
    
    return (
        <div>
            <Head>
            <title> {recipe.name} </title>
            <meta name="description" content="Generated by create next app" />
            </Head>
            {JSON.stringify(recipe)}
            <div className='p-5 m-5 bg-white max-w-md'>
                <div id='header' className='bg-white m-10'>
                    <h1 className='uppercase font-bold	'>RECIPE: {recipe.name} </h1>
                    <h1 className='uppercase	'>By: </h1>
                </div>
                <hr/>
                <div id='title' className=' m-10'>
                    <h1 className='uppercase	'>Ingredients: </h1>
                    <h1 className='uppercase'>Time: </h1>
                    <h1 className='uppercase'>Dificulty: {recipe.dificulty} </h1>
                    <h1 className='uppercase'>Ingredients: </h1>
                </div>
                <hr/>
                <div id='body' className=' m-10'>
                    <h1 className='uppercase	'>Body: </h1>
                </div>
                 
                
                
 
            </div>
        </div>
    )
}

export const getServerSideProps : GetServerSideProps = async ({params}) => {

    dbConnect();

    const recipe = await Recipe.findById(params.id).lean();

    return {props: {recipe: {...recipe, _id: recipe._id.toString()}}};
}