import Head from "next/head"
import RecipesList from "../components/RecipesList"
import { GetServerSideProps } from "next"
import dbConnect from "../lib/dbConnect"
import Recipe from "../models/Recipe"
import Ingredient from "../models/Ingredient"
import Category from "../models/Category"

export default function Home({recipes}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RecipesList  recipes={recipes}/>
      
      
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {

  await dbConnect()
  const results = await Recipe.find({}).lean()

  const ingredient_array = []
  const category_array = []
  await Promise.all(
    results.map(async (result) => {
      ingredient_array.push(await Ingredient.find({}).where('recipe_id').equals(result._id).lean());
      category_array.push(await Category.find({}).where('recipe_id').equals(result._id).lean());
    })
  )

  
  const recipes = results.map((doc, index) => (    
    {
    ...doc,
    ...{_id: doc._id.toString()},
    ...{ingredients: ingredient_array[index]},
    ...{categories: category_array[index]}
  }))

  return {props: { recipes:JSON.parse(JSON.stringify(recipes)) }}
}